services:
  redis:
    build:
        context: ./redis
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_dev_data:/data
    command: [ "redis-server", "--appendonly", "yes", "--appendfsync", "everysec" ]

  webui_be:
    build:
      context: ./
    container_name: webui_be
    restart: always
    ports:
      - 4003:4003
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - DISCORD_TOKEN_URI=${DISCORD_TOKEN_URI}
      - DISCORD_USER_URI=${DISCORD_USER_URI}
      - FRONT_REDIRECT_URI=${FRONT_REDIRECT_URI}
      - REGISTER_URI=${REGISTER_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}


volumes:
  redis_dev_data:
